### ISSUE TITLE
User müssen anderen Usern folgen können bzw. nicht mehr folgen können

### ISSUE THREAD

**Issue by dnsdev** [jmennen/group5#51]

**Comment by dnsdev** [comment]
NEW

**Comment by jmennen** [comment]
Die Möglichkeit anderen Usern zu folgen. Wenn man einem User folgt sieht man dessen öffentliche Posts sowie alle Posts aus Kreisen in die man einsortiert wurde.

User können beliebig vielen anderen usern folgen

User können bestimmen anderen Usern nicht länger zu folgen

User können sich eine Liste ihrer Follower anzeigen

**Comment by jmennen** [comment]
CHANGE: New Story
