### ISSUE TITLE
User können die für sie sichtbare Kreisnachrichten von anderen Usern sehen

### ISSUE THREAD

**Issue by dnsdev** [jmennen/group5#53]

**Comment by jmennen** [comment]
Sowohl in ihrem Stream als auch auf dem Profil des jeweiligen postenden Nutzers. Es sind nur "public" Nachrichten sowie Nachrichten aus Kreisen, in welche der Follower vom Poster einsortiert wurde, sichtbar.

**Comment by jmennen** [comment]
CHANGE: New Story
